### ISSUE TITLE
Maximum size of the set

### ISSUE THREAD

**Issue by craigfrancis** [privacycg/first-party-sets#16]
Should there be an explicit limit to how many domains are included in the first-party-set?

I'm assuming needing more than 5 would be unlikely... where 1,000+ would be very bad.

**Comment by krgovind** [comment]
Thanks for the question!

Were you thinking of the domain limit as being something to aid ergonomics / prevent bloat; or to prevent abuse?

We did propose a size limit in a previous iteration of the design, but primarily as a mitigation against abuse. 

In the current version of the proposal, we depend on the "UA Policy" enforcement to prevent abuse. Such a policy provides an opportunity to enforce more meaningful/qualitative requirements, such as around ownership.

**Comment by craigfrancis** [comment]
Both really; my first thought was about ways to abuse this feature (e.g. ad networks), then I though about how a long list would look (assuming some kind of UI to “provide transparency to users”), and how that would work / break things (e.g. a company that owns 8 related sites, surely it’s fine to add one more, and another, and another, etc).

I suppose it makes sense the UA Policy will cover this, as you’re right, you should “expect the UA policies to evolve over time as use cases and abuse scenarios come up.”

I must confess, I’m a feeling a little uneasy about this proposal, but I suspect that’s just because it’s changing one of the fundamental things I’ve assumed would always be the case (the insulation between sites).
