### ISSUE TITLE
State clearing vs. changing the partition key

### ISSUE THREAD

**Issue by davidben** [privacycg/first-party-sets#26]
The explainer currently says "first-party set state must be cleared whenever other state for some first-party is cleared". This is so that, as domains move between sets, they don't link user data across all the partitions they've historically been in. This means the system needs to pay attention to state transitions, which gets a bit fussy.

Supposing we end up with something like this, perhaps we should recast this as simply saying your storage partition key incorporates the FPS owner. If your owner changes, you lose access to your old partition and can't correlate new activity with anything from before. We need to partition storage anyway, so that should cover things.

I think this is functionally equivalent, with a few footnotes:

* If A picks up a lot of state under partition P1, then moves to partition P2, the old (A, P1) state is still there but is now unreachable. The browser will probably want to expire/evict that or otherwise place limits. I think this is somewhat an extension of storage partitioning's existing increased pressure on storage limits.

* If A quickly switches from partition P1, to partition P2, then back to P1, the current model wipes (A, P1) on the first transition, so the second transition starts from empty again. The new model gets A back to the old state, assuming the browser hasn't since expired it, see above.

* Live documents continue to need to be treated as state, and the reload (analogy: `Clear-Site-Data: executionContexts`) is still needed. That said, race conditions are fine as long as the partition is fixed for the lifetime of the document. Documents in the process of being unloaded will have no access to the new partition, just the soon-to-be-disconnected old partition.

(This also ties into what @erik-anderson mentioned around partitioning schemes for top-level sites acting on behalf of other ones if we end up exploring that. Though, as Erik notes, that brings additional complexities around user understanding.)

**Comment by johannhof** [comment]
It seems like state clearing is the more pragmatic and realistic option here. It isn't clear whether we want to or can standardize keying cookies or storage on FPS given that most browsers don't plan to relax cookie restrictions based on FPS anyway, and there are security considerations especially around keying cache and storage on FPS. With state clearing it's easier to specify the correct behavior in a single place.

Closing this on behalf of @krgovind
