### ISSUE TITLE
[VK Company Feedback] FPS domains limit

### ISSUE THREAD

**Issue by NekR** [privacycg/first-party-sets#71]
Hi! What is planned limit on domains in single FPS and what would be "too big" for browsers to handle effectively?

For example, we probably have thousands of domains. They all aren't probably needed in FPS, but it certainly might be needed to include all of them in there at some point.

**Comment by krgovind** [comment]
@NekR - The question of limiting the size of a set is being discussed on #29, could you please comment on that issue instead? It would be useful if you can think about how many of these domains need to be in the same set. Do all of these thousands of domains interact with each other, or have a user flow that encompasses all the domains?

The question of appropriate limits is still an open question, but we're looking for feedback to help inform that decision.
